name: Node.js Package

on:
  release:
    types: [published]

jobs:
  version:
    runs-on: ubuntu-latest
    steps:    
      - uses: actions/github-script@v3
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        id: set-result
        with:
          script: return context.ref.replace('/refs/tags/', '')
          result-encoding: string
      - name: Get result
        run: echo "${{steps.set-result.outputs.result}}"
      - name: Set Version
        run: npm version --no-git-tag-version "${{steps.set-result.outputs.result}}"
    
  build:
    needs: version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: npm ci

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
